# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpc_code_expand_cpp <- function(cpc_3_digit, cpc_2_digit) {
    .Call(`_gtalibrarybeta_cpc_code_expand_cpp`, cpc_3_digit, cpc_2_digit)
}

cpc_to_hs_cpp <- function(hs_codes, cpc_codes, codes) {
    .Call(`_gtalibrarybeta_cpc_to_hs_cpp`, hs_codes, cpc_codes, codes)
}

datefunction <- function(start, end, current_date, current_year_todate = TRUE) {
    .Call(`_gtalibrarybeta_datefunction`, start, end, current_date, current_year_todate)
}

gta_code_converter_cpp <- function(codes_2012, codes_vintage, codes) {
    .Call(`_gtalibrarybeta_gta_code_converter_cpp`, codes_2012, codes_vintage, codes)
}

count_interventions_cpp <- function(start, end, count_by) {
    .Call(`_gtalibrarybeta_count_interventions_cpp`, start, end, count_by)
}

